// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.9
// source: forward.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestForward struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *RequestForward) Reset() {
	*x = RequestForward{}
	if protoimpl.UnsafeEnabled {
		mi := &file_forward_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestForward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestForward) ProtoMessage() {}

func (x *RequestForward) ProtoReflect() protoreflect.Message {
	mi := &file_forward_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestForward.ProtoReflect.Descriptor instead.
func (*RequestForward) Descriptor() ([]byte, []int) {
	return file_forward_proto_rawDescGZIP(), []int{0}
}

func (x *RequestForward) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type RequestForwardResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *RequestForwardResponse) Reset() {
	*x = RequestForwardResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_forward_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestForwardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestForwardResponse) ProtoMessage() {}

func (x *RequestForwardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forward_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestForwardResponse.ProtoReflect.Descriptor instead.
func (*RequestForwardResponse) Descriptor() ([]byte, []int) {
	return file_forward_proto_rawDescGZIP(), []int{1}
}

func (x *RequestForwardResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RequestForwardResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_forward_proto protoreflect.FileDescriptor

var file_forward_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x66, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x24, 0x0a, 0x0e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x46, 0x0a, 0x16,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x32, 0x4a, 0x0a, 0x07, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x12,
	0x3f, 0x0a, 0x05, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x12, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x1a,
	0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x46,
	0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_forward_proto_rawDescOnce sync.Once
	file_forward_proto_rawDescData = file_forward_proto_rawDesc
)

func file_forward_proto_rawDescGZIP() []byte {
	file_forward_proto_rawDescOnce.Do(func() {
		file_forward_proto_rawDescData = protoimpl.X.CompressGZIP(file_forward_proto_rawDescData)
	})
	return file_forward_proto_rawDescData
}

var file_forward_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_forward_proto_goTypes = []interface{}{
	(*RequestForward)(nil),         // 0: proto.RequestForward
	(*RequestForwardResponse)(nil), // 1: proto.RequestForwardResponse
}
var file_forward_proto_depIdxs = []int32{
	0, // 0: proto.Forward.Route:input_type -> proto.RequestForward
	1, // 1: proto.Forward.Route:output_type -> proto.RequestForwardResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_forward_proto_init() }
func file_forward_proto_init() {
	if File_forward_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_forward_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestForward); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_forward_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestForwardResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_forward_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_forward_proto_goTypes,
		DependencyIndexes: file_forward_proto_depIdxs,
		MessageInfos:      file_forward_proto_msgTypes,
	}.Build()
	File_forward_proto = out.File
	file_forward_proto_rawDesc = nil
	file_forward_proto_goTypes = nil
	file_forward_proto_depIdxs = nil
}
